### ISSUE TITLE
Language Mess with Console Language from Server (Fabric 1.21.1)

### ISSUE THREAD

**Issue by suerion** [chimericdream/athenaeum-mod#1]
Hey, i had found a little aestethic bug for Servers.

After adding The Athenaeum for Fabric 1.21.1 it messes with the console texts

```Preparing spawn area: 2%``` is the normal one

```[23:12:13] [Worker-Main-4/INFO]: menu.preparingSpawn``` after adding 

An other Modder has sayin, that is only a missing tranlation key. ;)

**Comment by suerion** [comment]
Had also found this issue on fabric github 

https://github.com/FabricMC/fabric/issues/2943


Fabric Discord
https://discord.com/channels/507304429255393322/566276937035546624/1297750020589748265

**Comment by chimericdream** [comment]
Ugh, I remember something like this happening before, but I figured they would have fixed it by now. I'll try to find a different way to modify the book generation names. In the worst case, I can remove the overrides, but I'd prefer to keep the "1st/2nd/... Edition" names if possible.

Thanks for taking the time to let me know!

**Comment by suerion** [comment]
Hey, newest Fabric API does fix this issue ;)
https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1

**Comment by suerion** [comment]
Ah yea, would close this issue ;) to get clean issues
